name: Build EMS FW

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repo (no SSH, use token)
      uses: actions/checkout@v3
      with:
        submodules: false
        fetch-depth: 1

    - name: Set up SSH for private submodules
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GH_SSH_KEY_FOR_FEDOR }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global url."git@github.com:".insteadOf "https://github.com/"

    - name: Manually checkout submodules over SSH
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive

    - name: Set environment variables
      id: vars
      run: |
        REPO_NAME=$(basename $GITHUB_REPOSITORY)
        DATE_STR=$(date +%d%m%Y)
        COMMIT_HASH=$(git rev-parse --short HEAD)
        ARCHIVE_NAME="${REPO_NAME}_${DATE_STR}_${COMMIT_HASH}.zip"
        echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
        echo "DATE_STR=$DATE_STR" >> $GITHUB_ENV
        echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
        echo "ARCHIVE_NAME=$ARCHIVE_NAME" >> $GITHUB_ENV

    - name: Archive raw source folder (before build)
      run: |
        zip -r "${ARCHIVE_NAME}" . -x ".git/*"

    - name: Upload raw source artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARCHIVE_NAME }}
        path: ${{ env.ARCHIVE_NAME }}
        retention-days: 7

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1.1.0
      with:
        esp_idf_version: v5.3.1
        target: esp32s3
        path: './'
