name: Build EMS FW

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH for private submodules
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GH_SSH_KEY_FOR_FEDOR }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Checkout repo with submodules using SSH key
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 1
        ssh-key: ${{ secrets.GH_SSH_KEY_FOR_FEDOR }} 

    - name: Set environment variables
      id: vars
      run: |
        echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV
        echo "DATE_STR=$(date +%d%m%Y)" >> $GITHUB_ENV
        echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "ARCHIVE_NAME=${{ env.REPO_NAME }}_${{ env.DATE_STR }}_${{ env.COMMIT_HASH }}.zip" >> $GITHUB_ENV

    - name: Archive raw source folder (before build)
      run: |
        cd ..
        zip -r "${ARCHIVE_NAME}" $(basename $GITHUB_REPOSITORY)

    - name: Upload raw source artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARCHIVE_NAME }}
        path: ../${{ env.ARCHIVE_NAME }}

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1.1.0
      with:
        esp_idf_version: v5.3.1
        target: esp32s3
        path: './'
